### ISSUE TITLE
Issues with caching

### ISSUE THREAD

**Issue by ellessenne** [r-lib/styler#592] opened 2020-02-13 10:13 UTC
Hi @lorenzwalthert,
I am having issues with caching (maybe related to #584 #585?).
I find it hard to reproduce, but at times I notice that lines that have a comment after some code, e.g.

```r
x <- 1 # comment
```

get styled to something like

```r
# comment
```

The comment seems to "take over" and cause deletion of the code that comes before it.

I tried to get a reproducible example but it seems quite random at the moment, sorry about that. 
I think the issue might be related to caching as if I try running `cache_clear()` and re-styling the file, then it works fine.

Let me know if you have any idea on how to reproduce this behaviour. Thanks!

**Comment by lorenzwalthert** [comment] 2020-02-13 11:08
Thanks @ellessenne, it's really important we can make sure styler does not do that. Are you using `v1.3.0`, i.e. the current CRAN version? Also, how are you accessing the functionality? Via Addin or `style_file()`? Also note that the cache is only active when you have sent an expression through styler before *and* the expression was already corresponding to the style guilde in use.

**Comment by lorenzwalthert** [comment] 2020-02-13 11:12
I was able to reproduce this problem in a way I don't know how to reproduce it again :scream: .

**Comment by ellessenne** [comment] 2020-02-13 11:14
I am indeed using the latest version from CRAN.

I could see this behaviour with both `style_file()` and `style_text()`, but I could not reproduce it reliably (I have been trying to create a `reprex` but I still can't identify a failure pattern). Still trying!

**Comment by lorenzwalthert** [comment] 2020-02-13 11:33
Here is a reprex: 

``` r
library(styler)
cache_activate()
#> Using cache 1.3.0 at ~/.Rcache/styler/1.3.0.
style_text("1")
#> 1
style_text("1 # comment")
#> # comment
```

<sup>Created on 2020-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ellessenne** [comment] 2020-02-13 11:36
Thanks! I can reproduce that.

I couldn't reproduce the behaviour with the code below, but I got another error from `style_text`:

```r
library(styler)
library(reprex)

styler::cache_deactivate()
styler::cache_clear(ask = F)
styler::cache_activate()

reprex({
  library(styler)

  text <- '
  ### comment
  x = 1 ### comment
  y = 2 # comment
  x<-1 ###comment
  y <- 2 # comment
  "a string here"
  
  # something something
  tau1 = 1 # here?
  '

  tmpf <- tempfile(fileext = ".R")
  fileConn <- file(tmpf)
  writeLines(text = text, tmpf)
  close(fileConn)
  cat(readLines(tmpf), sep = "\n")

  styler::style_file(path = tmpf)
  cat(readLines(tmpf), sep = "\n")

  styler::style_file(path = tmpf)
  cat(readLines(tmpf), sep = "\n")

  styler::style_text(text)
})
```

The rendered reprex is:

``` r
library(styler)

text <- '
### comment
x = 1 ### comment
y = 2 # comment
x<-1 ###comment
y <- 2 # comment
"a string here"

# something something
tau1 = 1 # here?
'

tmpf <- tempfile(fileext = ".R")
fileConn <- file(tmpf)
writeLines(text = text, tmpf)
close(fileConn)
cat(readLines(tmpf), sep = "\n")
#> 
#> ### comment
#> x = 1 ### comment
#> y = 2 # comment
#> x<-1 ###comment
#> y <- 2 # comment
#> "a string here"
#> 
#> # something something
#> tau1 = 1 # here?

styler::style_file(path = tmpf)
#> Styling  1  files:
#>  C:\Users\alegas\AppData\Local\Temp\RtmpIrH2W4\file181447155c23.R i 
#> ----------------------------------------------------------------
#> Status   Count   Legend 
#> v    0   File unchanged.
#> i    1   File changed.
#> x    0   Styling threw an error.
#> ----------------------------------------------------------------
#> Please review the changes carefully!
cat(readLines(tmpf), sep = "\n")
#> 
#> ### comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> "a string here"
#> 
#> # something something
#> tau1 <- 1 # here?

styler::style_file(path = tmpf)
#> Styling  1  files:
#>  C:\Users\alegas\AppData\Local\Temp\RtmpIrH2W4\file181447155c23.R v 
#> ----------------------------------------------------------------
#> Status   Count   Legend 
#> v    1   File unchanged.
#> i    0   File changed.
#> x    0   Styling threw an error.
#> ----------------------------------------------------------------
cat(readLines(tmpf), sep = "\n")
#> 
#> ### comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> "a string here"
#> 
#> # something something
#> tau1 <- 1 # here?

styler::style_text(text)
#> Error in rep("", start_line - 1): invalid 'times' argument
```

<sup>Created on 2020-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lorenzwalthert** [comment] 2020-02-13 11:36
The problem happens when multiple expressions are on one line and only some of them are cached. All expressions on the same line are put in one block and processed together. However, in `extract_termials()`, we only extract expressions from the current nest when the token is a terminal. Otherwise, we extract them from children. For some reason to investigate, the cached expression is not marked as a terminal, hence, the child is extracted, which is `NULL`.

**Comment by lorenzwalthert** [comment] 2020-02-13 11:37
Ok, please open another issue for this one as it seems unrelated.

**Comment by lorenzwalthert** [comment] 2020-02-13 11:48
I fixed the first problem (not yet sure it's the best way to go about it but anyways) in #593. Can you check if your second problem also appears with this this version?
```r
remotes::install_github('r-lib/styler#593')
```

**Comment by lorenzwalthert** [comment] 2020-02-13 11:49
I think the solution to the problem is to make all cached expressions behave exactly as terminals at the time we drop their children and make the parse table shallow.

**Comment by lorenzwalthert** [comment] 2020-02-13 11:50
ok, no don't try it, test are failing.

**Comment by ellessenne** [comment] 2020-02-13 11:57
I tried before reading your latest message and `style_text` seemed to process the first expression only:

``` r
library(styler)

styler::cache_deactivate()
#> Deactivated cache.
styler::cache_clear(ask = F)
styler::cache_activate()
#> Using cache 1.3.9000 at C:\Users\alegas\AppData\Local\R\R.cache/styler/1.3.9000.

text <- '
### comment
x = 1 ### comment
y = 2 # comment
x<-1 ###comment
y <- 2 # comment
"a string here"

# something something
tau1 = 1 # here?
'

styler::style_text(text)
#> 
#> ### comment

styler::cache_deactivate()
#> Deactivated cache.
styler::cache_clear(ask = F)

styler::style_text(text)
#> 
#> ### comment
```

<sup>Created on 2020-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ellessenne** [comment] 2020-02-13 11:57
Should I open a separate issue?

**Comment by lorenzwalthert** [comment] 2020-02-13 13:13
No I think now it works, doesn't it?

**Comment by lorenzwalthert** [comment] 2020-02-13 13:14
I get this: 

``` r
library(styler)

styler::cache_deactivate()
#> Deactivated cache.
#> Deactivated cache.
styler::cache_clear(ask = F)
styler::cache_activate()
#> Using cache 1.3.9000 at /Users/lorenz/Library/Caches/R/R.cache/styler/1.3.9000.
#> Using cache 1.3.9000 at C:\Users\alegas\AppData\Local\R\R.cache/styler/1.3.9000.

text <- '
### comment
x = 1 ### comment
y = 2 # comment
x<-1 ###comment
y <- 2 # comment
"a string here"

# something something
tau1 = 1 # here?
'

styler::style_text(text)
#> 
#> ### comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> "a string here"
#> 
#> # something something
#> tau1 <- 1 # here?
#> 
#> ### comment

styler::cache_deactivate()
#> Deactivated cache.
#> Deactivated cache.
styler::cache_clear(ask = F)

styler::style_text(text)
#> 
#> ### comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> "a string here"
#> 
#> # something something
#> tau1 <- 1 # here?
#> 
#> ### comment
```

<sup>Created on 2020-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ellessenne** [comment] 2020-02-13 13:40
The second issue is not fixed yet for me, I still get that error when I re-style an expression that is cached:

``` r
  library(styler)
  
  styler::cache_deactivate()
#> Deactivated cache.
  styler::cache_clear(ask = F)
  styler::cache_activate()
#> Using cache 1.3.9000 at C:\Users\alegas\AppData\Local\R\R.cache/styler/1.3.9000.

  text <- '
### comment
x = 1 ### comment
y = 2 # comment
x<-1 ###comment
y <- 2 # comment
"a string here"

# something something
tau1 = 1 # here?
'
  
  styler::style_text(text)
#> 
#> ### comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> "a string here"
#> 
#> # something something
#> tau1 <- 1 # here?
  styler::style_text(text)
#> Error in rep("", start_line - 1): invalid 'times' argument

  styler::cache_deactivate()
#> Deactivated cache.
  styler::cache_clear(ask = F)

  styler::style_text(text)
#> 
#> ### comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> "a string here"
#> 
#> # something something
#> tau1 <- 1 # here?
  styler::style_text(text)
#> 
#> ### comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> x <- 1 ### comment
#> y <- 2 # comment
#> "a string here"
#> 
#> # something something
#> tau1 <- 1 # here?
```

<sup>Created on 2020-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lorenzwalthert** [comment] 2020-02-13 13:43
I see, sorry.

**Comment by lorenzwalthert** [comment] 2020-02-13 14:55
Ok now when you try #595 I think it's all fixed.
```r
remotes::install_github('r-lib/styler#595')
```

Can you confirm?

**Closed** 2020-02-13 15:02 UTC
Labels: Complexity: Unassigned, Priority: Critical, Status: WIP, Type: Bug

**Comment by ellessenne** [comment] 2020-02-14 07:56
Hi @lorenzwalthert, I just got around trying the new release (1.3.1) and I don't see the issues we were able to reproduce in this thread. Looking good!
Thanks a lot! 😃

**Comment by lorenzwalthert** [comment] 2020-02-14 08:06
Thanks @ellessenne. When I saw the notification for your post, I was aleady afraid you found a new bug haha. Thank you for reporting. You found two major bugs. :+1:

**Comment by ellessenne** [comment] 2020-02-14 08:41
Ahah no worries (for now 😛) - and thanks again for fixing this so quickly, I really use styler a lot and appreciate your work very much!

**Comment by lorenzwalthert** [comment] 2020-02-14 08:49
Are you using https://github.com/lorenzwalthert/precommit also?

**Comment by ellessenne** [comment] 2020-02-14 08:53
I am not (am a bit wary about automated actions before committing to git), but I checked that out before 😃

**Comment by lorenzwalthert** [comment] 2020-02-14 09:02
It does style the file and if it changes the file, git won't make the commit. You can then inspect the diff with git, add it if you approve and if not, `git commit --no-verify` to commit as is. If the file is not modified with the hook, the commit will be made directly. No magic there :smile:, but I can understand the barrier for using it.

**Comment by ellessenne** [comment] 2020-02-14 09:26
Ah, that's cool - I (wrongly) assumed that the commit was going through no matter what! I'll have to check it out again then 😃
