### ISSUE TITLE
Incorrect formatting due to caching

### ISSUE THREAD

**Issue by renkun-ken** [r-lib/styler#594] opened 2020-02-13 11:59 UTC
```r
mtcars %>%
  f() # hello
```

is formatted to

```r
# hello
```

It won't happen if the comment is removed or `%>%` is replaced with `+`.

**Comment by lorenzwalthert** [comment] 2020-02-13 13:02
This probably only happens under some circumstances. Please do not `cache_clear()` because then your problem won't be reproducible anymore I assume. Can you share the cache directory with me for debugging? You can find it with `cache_info()`.

**Comment by lorenzwalthert** [comment] 2020-02-13 13:04
Here is a reprex:

``` r
library(styler)
cache_clear(ask = FALSE)
cache_activate()
#> Using cache 1.3.9000 at /Users/lorenz/Library/Caches/R/R.cache/styler/1.3.9000.
# style_text("f() # hello")
style_text("mtcars")
#> mtcars
style_text("mtcars %>%
  f()")
#> mtcars %>%
#>   f()

style_text("mtcars %>%
  f() # ")
#> #
```

<sup>Created on 2020-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lorenzwalthert** [comment] 2020-02-13 13:05
It seems as it is a duplicate of #592. At least the corresponding PR in #593 fixes it.

**Comment by lorenzwalthert** [comment] 2020-02-13 13:40
Closed with #593.

**Closed by lorenzwalthert** 2020-02-13 13:40 UTC
Labels: Complexity: Unassigned, Priority: Critical, Status: WIP, Type: Bug
