### ISSUE TITLE
`styler::style_file()` does not handle non-roman characters properly

### ISSUE THREAD

**Issue by jooyoungseo** [r-lib/styler#908] opened 2022-01-23 21:49 UTC
I have found that an R script containing gnon-roman characters (e.g., Korean) is not converted correctly in `styler::style_file()`.

FYI, the file is encoded in UTF-8.

## Korean R

Save the following file content in UTF-8 encoding (also attached here).

[korean.R.txt](https://github.com/r-lib/styler/files/7921504/korean.R.txt)
``` r
# 한국어
hist(airquality$Ozone,col='red')
```

## Reprex

``` r
styler::style_file("korean.R")
```

## Results

``` r
# <U+D55C><U+AD6D><U+C5B4>
hist(airquality$Ozone, col = "red")
```

## Session Info

``` r
session_info()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Locale:
#>   LC_COLLATE=English_United States.1252 
#>   LC_CTYPE=English_United States.1252   
#>   LC_MONETARY=English_United States.1252
#>   LC_NUMERIC=C                          
#>   LC_TIME=English_United States.1252    
#> system code page: 65001
#> 
#> Package version:
#>   base64enc_0.1.3   callr_3.7.0       cli_3.1.0         clipr_0.7.1      
#>   compiler_4.1.2    crayon_1.4.2      digest_0.6.29     ellipsis_0.3.2   
#>   evaluate_0.14     fansi_1.0.2       fastmap_1.1.0     fs_1.5.2         
#>   glue_1.6.0        graphics_4.1.2    grDevices_4.1.2   highr_0.9        
#>   htmltools_0.5.2   jquerylib_0.1.4   jsonlite_1.7.3    knitr_1.37       
#>   lifecycle_1.0.1   magrittr_2.0.1    methods_4.1.2     pillar_1.6.4     
#>   pkgconfig_2.0.3   processx_3.5.2    ps_1.6.0          purrr_0.3.4      
#>   R.cache_0.15.0    R.methodsS3_1.8.1 R.oo_1.24.0       R.utils_2.11.0   
#>   R6_2.5.1          rematch2_2.1.2    reprex_2.0.1      rlang_0.4.12     
#>   rmarkdown_2.11    rprojroot_2.0.2   rstudioapi_0.13   stats_4.1.2      
#>   stringi_1.7.6     stringr_1.4.0     styler_1.6.2.9000 tibble_3.1.6     
#>   tinytex_0.36      tools_4.1.2       utf8_1.2.2        utils_4.1.2      
#>   vctrs_0.3.8       withr_2.4.3       xfun_0.29         yaml_2.2.1
```

**Comment by lorenzwalthert** [comment] 2022-01-23 22:43
Duplicate of #907 and #847. TL;DR: wait for R 4.2 if you are on Windows (or install R devel) and install the dev version of {styler} so far to throw an error on styling a file containing Unicode characters instead of producing Code that is not parsable.

**Closed by lorenzwalthert** 2022-01-23 22:43 UTC
