### ISSUE TITLE
Documentation not rendered correctly

### ISSUE THREAD

**Issue by behrman** [r-lib/styler#992] opened 2022-09-03 17:36 UTC
The transformed code in some documentation is not rendered correctly. I've attached a screenshot from [Get started](https://styler.r-lib.org/articles/styler.html). The same is true for [styler 1.4.0](https://lorenzwalthert.netlify.app/post/styler-1-4-0/). I'm using a Mac and the problem was the same on Firefox, Chrome, and Safari.

![Screen Shot 2022-09-03 at 10 33 08 AM](https://user-images.githubusercontent.com/15931497/188282003-d53346dc-bf73-4d95-921f-f63d3649f075.png)

**Comment by IndrajeetPatil** [comment] 2022-09-03 18:29
Thanks for the report.

This is duplicate of https://github.com/r-lib/styler/issues/954

If you visit the website for the [development version](https://styler.r-lib.org/dev/articles/styler.html) of the package, you will see that this is no longer the case.

So, once `{styler}` is updated on CRAN, the release version should also be free of this issue.

**Closed by IndrajeetPatil** 2022-09-03 18:29 UTC
