### ISSUE TITLE
feature request: removing empty lines in function argument specifications

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#716] opened 2021-01-20 16:06 UTC
Feel free to close this if you feel the gain here is inconsequential for the work needed to support this feature, but I was expecting the following code 

``` r
styler::style_text(
  "foo <- function(
                  a,
                  b = 2,
                  c = 3,
                  d = 4) {
    print('hi')
  }"
)
#> foo <- function(
#>                 a,
#>                 b = 2,
#>                 c = 3,
#>                 d = 4) {
#>   print("hi")
#> }
```

<sup>Created on 2021-01-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

to be styled as-

```r
foo <- function(a,
                b = 2,
                c = 3,
                d = 4) {
  print("hi")
}
```

I couldn't find relevant discussion about this in the `tidyverse` style guide, but does that make sense to you?

**Comment by lorenzwalthert** [comment] 2021-01-20 17:29
Makes complete sense. Actually kind of a duplicate of https://github.com/r-lib/styler/issues/549, but not covered in the associated PR (although specifically mentioned as an example).

**Closed** 2021-01-31 16:18 UTC
Labels: Complexity: Low, Priority: Medium, Status: Unassigned, Type: Bug
