### ISSUE TITLE
styler always sends an e-mail when commenting on the repo

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#1008] opened 2022-09-26 16:36 UTC
Every time I interact on the styler repo, I get a rather dull e-mail:

https://screenshot.googleplex.com/69nkbtPXwk42pNs

From poking around a little bit, it's caused by the pr-commands GHA:

https://github.com/r-lib/styler/blob/1f4437bf81c807da713eb1ec78b08e6a78002617/.github/workflows/pr-commands.yaml

(note: `name: Commands` which matches the e-mail).

I haven't quite figured out how to fix this -- should there be a placeholder job that always runs & succeeds immediately? That way when neither of the `/document` and `/style` commands are issued, at least something runs? Seems a bit silly. I haven't been able to find any related issues though.

**Comment by IndrajeetPatil** [comment] 2022-09-26 16:41
This happens to me as well, and, a while back, I had reported it [here](https://github.com/r-lib/styler/issues/928#issuecomment-1065920197). 

So, yes, reproducible and is definitely something that should be fixed.

**Comment by lorenzwalthert** [comment] 2022-09-28 07:04
I agree. Maybe worth investigating how our GHA files differ from the standard ones in r-lib/actions? Also, we don't actually need `/style` and `/document` actions really, because we have pre-commit.

**Comment by IndrajeetPatil** [comment] 2022-09-28 07:06
Yeah, I'd argue that we just get rid of the `pr_commands.yaml` in favour of `precommit`.

**Closed** 2022-10-01 16:57 UTC
