### ISSUE TITLE
How to config styler?

### ISSUE THREAD

**Issue by kalaschnik** [r-lib/styler#919] opened 2022-02-28 09:47 UTC
I sometimes run into the case where I want to provide information about parameters. Yet, when using styler my function goes from this:

```
my_fun <- function(
    param1,
    param2,
    param3 = list(start = 1, end = nrow(df)), # defaults to include all rows of df
    param4 = c("start", "end"), # some longer description which has a length like this comment
    param5 = FALSE) {

  print("yada yada")
}

```

into this:

```
my_fun <- function(param1,
                   param2,
                   param3 = list(start = 1, end = nrow(df)), # defaults to include all rows of df
                   param4 = c("start", "end"), # some longer description which has a length like this comment
                   param5 = FALSE) {

   print("yada yada")
}
```

This creates long lines with over 100 characters. Anyway, is there a way to set up a config file to enforce `double-indent style` (https://style.tidyverse.org/functions.html#long-lines-1)?

**Comment by lorenzwalthert** [comment] 2022-02-28 10:27
There is currently an open issue for double indent with #845 but it's not implemented yet. So I'd consider that a duplicate of #845. Tangent issue: #247.

**Closed by lorenzwalthert** 2022-02-28 10:27 UTC

**Comment by kalaschnik** [comment] 2022-02-28 10:49
Just for clarification; as of now there is no way to config styler?

**Comment by lorenzwalthert** [comment] 2022-02-28 10:55
There is [a whole vignette](https://styler.r-lib.org/articles/styler.html) on the topic of customization, but as far as double indent goes, you can't (unless you implement [your own style guide](https://styler.r-lib.org/articles/customizing_styler.html)).

**Comment by kalaschnik** [comment] 2022-02-28 12:49
Thanks for the link; there really should be a **[GETTING STARTED](https://styler.r-lib.org/articles/styler.html)** within the README.

I see that I can use transformers as an argument; yet, my question was related to having an external file such as: `.stylerrc` where I provide my own styler preferences without the need of repeating myself in function arguments.

**Comment by kalaschnik** [comment] 2022-02-28 18:18
Wooops; I just found this: https://github.com/r-lib/styler/issues/319. That was what I was looking for.
