### ISSUE TITLE
Preventing vertical styling of R expression (bquote)

### ISSUE THREAD

**Issue by PMassicotte** [r-lib/styler#695] opened 2020-11-19 18:25 UTC
Is it possible to prevent the styler package to reformat bquote/expression like this one?

```r
bquote(km ~ h^{-1})
```
At the moment, `styler` re-indent it vertically.

![Peek 2020-11-19 09-42](https://user-images.githubusercontent.com/4519221/99707023-e8c3a280-2a69-11eb-9311-c4ebc92017c2.gif)

It would be nice to be able to specify an option to only re-indent horizontally (i.e. add missing spaces).

For example,

```r
bquote(km~h^{-1})
```
would become (or whatever match the tidyverse rules)

```r
bquote(km ~ h ^ { -1 })
```
I think that would be greatly appreciated for people that use `bquote` or `expression` when making ggplot2 graphics for example.

**Comment by hadley** [comment] 2020-11-19 19:55
I think the root cause is the use of `{}`. Why not use `()`?

**Comment by PMassicotte** [comment] 2020-11-19 20:09
Unless I misunderstood your comment, using `()` is not producing the desired output:

``` r
library(ggplot2)

ggplot() +
  labs(x = bquote(km ~ h^(-1)))
```

![](https://i.imgur.com/tDFu4dl.png)

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment] 2020-11-19 20:36
Ah ok, this isn't really about `bquote()` then (since you could equally easily use `quote()` here), but about plotmath style mathematical formatting. I don't think that styler should handle this case because it would be challenging to automatically detect when your in a mathematical formula.

**Comment by lorenzwalthert** [comment] 2020-11-19 20:57
For curly braces, you could take advantage of the fact that curly-curly (`{{ }}`) is formatted differently than `{ }` without changing the result of the plotting.

```r
styler::style_text("ggplot() + labs(x = bquote(km ~ h^{{-1}}))")
#> ggplot() +
#>   labs(x = bquote(km ~ h^{{ -1 }}))
```

**Comment by lorenzwalthert** [comment] 2020-11-26 19:24
I think we can close this for now.

**Closed by lorenzwalthert** 2020-11-26 19:24 UTC
Labels: Complexity: Unassigned, Priority: Medium, Status: Unassigned, Type: Unassigned
