### ISSUE TITLE
Cannot Style Code When Script Is In Separate Window?

### ISSUE THREAD

**Issue by mvanaman** [r-lib/styler#1100] opened 2023-03-30 21:35 UTC
Hi,

I'm surprised no one has asked about this, or if they have, then I apologize for missing it in my search through the issues.

In an R script, when I highlight and run the code below, _styler_ returns the lovely reformatted code. However, if I click the "Show in new window" button, _then_ highlight the code and run `styler:::style_selection()`, I receive the error `! No code selected`.

Is this inherent to the _styler_ package or am I missing some necessary step that must be taken when the script is in its own window?

```
c("style", "me",
  "please"
)
styler:::style_selection()
```

Thank you for your time!
Matthew

**Comment by lorenzwalthert** [comment] 2023-03-31 10:03
Hi Matthew

Sorry I don't get what you mean. In RStudio? Can you upload a screenshot or screen cast?

**Comment by mvanaman** [comment] 2023-03-31 21:45
Sure, here are some annotated screenshots:

Code I want to style:
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/40613941/229238081-ac751e1a-5eda-417b-8d30-e5c99fae1d42.png">

Runs fine:
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/40613941/229238130-aa415117-e9d9-4cd5-a1f6-fc6cde357071.png">

Undo the style, move R script into its own window:
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/40613941/229238157-518fc90c-25ac-4dac-88ee-6f32190c59c0.png">

Try to style again, styler throws error:
<img width="1440" alt="4" src="https://user-images.githubusercontent.com/40613941/229238524-04f7ca2f-97a8-4bcf-9a53-c0ae460b815f.png">

Is that clearer?

**Comment by lorenzwalthert** [comment] 2023-03-31 22:03
Very clear now, thanks. Indeed that does not work. I am not sure but I think that's an {rstudioapi} problem. {styler} uses that package to figure out the selected code...

**Comment by lorenzwalthert** [comment] 2023-05-24 06:25
Are you running `styler:::style_selection()` explicitly or are you using the Addin to trigger the styling? Because you should not put `styler::style_selection()` in a script or similar.

**Comment by lorenzwalthert** [comment] 2024-02-01 17:24
@mvanaman please follow up or we assume this has been resolved.

**Comment by mvanaman** [comment] 2024-02-01 18:59
> Are you running `styler:::style_selection()` explicitly or are you using the Addin to trigger the styling? Because you should not put `styler::style_selection()` in a script or similar.

Sorry – it does not work when using the addin either.

**Comment by lorenzwalthert** [comment] 2024-02-02 03:11
Ok, I can reproduce it. Seems to be a limitation since when you click on the admin window, your active window is not the one where your code to style is (although in that window, the text remains highlighted). But if you have a short-cut assigned to the addin, it works for me, since your active window is the one with the code to style.

**Comment by lorenzwalthert** [comment] 2024-02-02 03:12
You can also see that c/p does not work for example on the highlighted code once you klick on the main window. So I am afraid I won't be able to fix that.

**Closed by lorenzwalthert** 2024-02-02 03:12 UTC
Labels: Type: Bug, Priority: Low, Complexity: Medium, Status: Unassigned

**Comment by mvanaman** [comment] 2024-02-02 16:19
Got it – thank you for checking this out, and for the shortcut tip! That's super helpful.
