### ISSUE TITLE
Style Active File addin does nothing

### ISSUE THREAD

**Issue by SimonDedman** [r-lib/styler#648] opened 2020-06-23 02:53 UTC
Per the title, this option does nothing for me.

Xubuntu 19.10
RStudio 1.3.1023
R 3.6.3

Selecting all text and doing Style Selection works perfectly. Happy to provide any further diagnostics info as required. I said Y to the R cache package question and haven't restarted since.

Cheers

**Comment by lorenzwalthert** [comment] 2020-06-23 07:05
Thanks @SimonDedman. Maybe it's a caching bug, like #646? To check this, can you run `styler::cache_clear()`, restart RStudio and try again. Before you do that, please save the file contents to another file so we can investigate the un-styled expression.

**Comment by SimonDedman** [comment] 2020-06-23 17:10
Morning Lorenz,

Works after restarting, happily. I forget the exact text which is prompted to the user (about the cache) but maybe for future builds you could add something like "please restart RStudio before using the 'style active file' addin". (Or just "please restart RStudio"!)

Cheers, have a good one.

**Comment by lorenzwalthert** [comment] 2020-06-24 07:33
You mean to indicate to restart RStudio after activating the cache?

**Comment by SimonDedman** [comment] 2020-06-24 17:13
Hiya,

Yep, correct. I thought 'style active file' might just work straight away. I figure people might try restarting anyway so it's not a huge issue, but easy enough to add to the helper prompt I guess?

**Comment by lorenzwalthert** [comment] 2020-06-24 18:03
Actually not, because the prompt is governed by `{R.cache}`. I can reproduce you issue, but even without restarting, I get things right when I trigger the Addin the second time. I think we can close this without doing anything further.

**Closed by lorenzwalthert** 2020-06-24 18:04 UTC
Labels: Complexity: Unassigned, Priority: Medium, Type: Bug

**Comment by lorenzwalthert** [comment] 2021-12-05 22:34
{R.cache} is not triggering a prompt anymore, as of [`styler >= 1.5.1`](https://styler.r-lib.org/news/index.html#minor-changes-and-fixes).
