### ISSUE TITLE
`{styler}` ignore directives trip up precommit workflow

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#1019] opened 2022-10-01 17:40 UTC
For example, see [this](https://github.com/r-lib/styler/actions/runs/3165499197/jobs/5154573191) for [this PR](https://github.com/r-lib/styler/pull/1018).

**Comment by lorenzwalthert** [comment] 2022-10-01 18:03
Seems to be resolved with a `pre-commit autoupdate` in https://github.com/r-lib/styler/pull/1018.

**Comment by IndrajeetPatil** [comment] 2022-10-01 18:04
Awesome! Thanks.

Btw, when precommit updates the PR, do you think this should trigger other workflows? Currently, this is not the case.

**Comment by lorenzwalthert** [comment] 2022-10-01 18:04
Well, not really fixed -.-. Will try to debug locally.

**Comment by lorenzwalthert** [comment] 2022-10-01 18:05
> Btw, when precommit updates the PR, do you think this should trigger other workflows? Currently, this is not the case.

It can't. It's by design of GitHub Actions that an action can't trigger another action. That's why pre-commit.ci is preferred

**Comment by IndrajeetPatil** [comment] 2022-10-01 18:07
Thanks for the explanation. Wasn't aware of this. Makes sense then.

**Comment by lorenzwalthert** [comment] 2022-10-03 19:29
Solved with #1018.

**Closed by lorenzwalthert** 2022-10-03 19:29 UTC
Labels: Type: Infrastructure
